config/routes.rb
Rails.application.routes.draw do
  resources :suppliers, only: [:new ,:create]
  resources :products, only: [:new ,:create]

  root to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import_file.rb
class ImportFile < ApplicationRecord
  has_one_attached :file

  def file_full_path
    ActiveStorage::Blob.service.send(:path_for, file.key)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier, primary_key: :code

  validates :supplier_code, :name, :price_cents, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products

  validates :code, :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @import_file = ImportFile.new
  end

  def create
    @import_file = ImportFile.new(import_params)

    if @import_file.file.attached? && @import_file.save
      ImportProductsJob.perform_later(@import_file.file_full_path)
    end

    redirect_to root_path
  end

  private

  def import_params
    params.require(:import_file).permit(:file)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
    @import_file = ImportFile.new
  end

  def create
    @import_file = ImportFile.new(import_params)

    if @import_file.file.attached? && @import_file.save
      ImportSuppliersJob.perform_later(@import_file.file_full_path)
    end

    redirect_to root_path
  end

  private

  def import_params
    params.require(:import_file).permit(:file)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvBulkImport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<ul>
  <li><%= link_to 'Import suppliers', new_supplier_path %></li>
  <li><%= link_to 'Import products', new_product_path %></li>
</ul>

app/views/products/new.html.erb
<%= form_for(@import_file, url: products_path, local: true) do |form| %>
  <%= form.file_field :file %>
  <br>
  <%= form.submit %>
<% end %>

app/views/suppliers/new.html.erb
<%= form_for(@import_file, url: suppliers_path, local: true) do |form| %>
  <%= form.file_field :file %>
  <br>
  <%= form.submit %>
<% end %>